### ISSUE TITLE
Link of "Example subclonal dynamics" is unavailable

### ISSUE THREAD

**Issue by HushWay** [caravagn/mobster_supp_data#2]
Hi, 

I want to understand the generation of simulated data, but the Supplementary Data vignette "[Example subclonal dynamics](https://caravagn.github.io/mobster/articles/Example_tumour_simulation.html)" is not found.  May the author update the link, please?

thanks,
liuwei

**Comment by caravagn** [comment]
Hi @HushWay 

Sorry some links changed over time but everything is still hosted at the main MOBSTER webpage

https://caravagnalab.github.io/mobster/articles/a7_Example_tumour_simulation.html

The tool adopted for simulation is TEMULATOR

https://t-heide.github.io/TEMULATOR/

**Comment by HushWay** [comment]
Hi @caravagn

Thank you for your quick reply. TEMULATOR is very cool, but I have a few questions to consult:
1. If it could take copy number alteration into consideration?
2. Could I turn the synthetic tumors into mutation files such as VCF files or even raw bam files for mutation calling? So that I can simulate tumors for subclonal reconstruction methods (such as PhyloWGS).

Thanks again,
Liuwei

**Comment by caravagn** [comment]
Hi @HushWay, 

1. No, but once you have generated the raw VAF you can adjust that by simulating mutation multiplicities and therefore adjust for absolute CNA values
2. TEMULATOR outputs just the raw data, so any transformation should be done by you. Creating a VCF file is quite simple since that is a mostly an augmented TXT format and there are several VCF-processing packages in R. For BAMs that is a bit more complicated as it requires other tools like BAMsurgeon etc. 

I hope this helps.

G

**Comment by HushWay** [comment]
@caravagn Your answer helped me a lot, thank you！

**Comment by caravagn** [comment]
@HushWay No problem, good luck with your work.
